### PR TITLE
Custom dimension picture

### PR DESCRIPTION
**Pull request by alexcastano**
This function gives the possibility to get images bigger than 200x200 which was my original problem.

### CODE REVIEW

**Comment by mweibel** [comment]
@alexcastano thanks for the PR. 👍 

I'd prefer if you refactor the `picture` function to allow for more parameters. Also in `custom_picture` there's the `type` missing it seems.

**Comment by mweibel** [comment]
ping?

**Comment by alexcastano** [comment]
Hi @mweibel 

Well, if you allow for more parameters you break the compatibility with older versions, I thought it was not a good idea. How should be the arguments of this function? Maybe type could be a tuple:

```elixir
 iex> Facebook.picture("<Some Id>", "small", "<Access Token>")
 iex> Facebook.picture("<Some Id>", {600, 600}, "<Access Token>")
```

**Comment by mweibel** [comment]
You could add a function with the same name with different amount of arguments though, no? 
Then call one from the other if possible.

**Comment by alexcastano** [comment]
I don't see to "type" function calls to dimension one, because facebook can change its criteria to match type => dimension at any time.

I'll change the name to the function ASAP :)

**Pull request closed without merging**
